### ISSUE TITLE
Unable to build config with `-su` in 1.6.5.x

### ISSUE THREAD

**Issue by dstreev** [cloudera-labs/hms-mirror#90]
Error:
2023-10-25 10:47:31,786 [main] ERROR Mirror.go(2178):Commandline args: []
2023-10-25 10:47:36,562 [main] INFO Mirror.go(2151):===================================================
2023-10-25 10:47:36,584 [main] INFO Mirror.go(2152):Running: hms-mirror v.1.6.5.3-SNAPSHOT
2023-10-25 10:47:36,584 [main] INFO Mirror.go(2153): with commandline parameters: -su
2023-10-25 10:47:36,584 [main] INFO Mirror.go(2154):===================================================
2023-10-25 10:49:14,479 [main] DEBUG Config.isExecute(565):Dry-run: ON
2023-10-25 10:49:14,492 [main] ERROR Config.setup(280):Problem 'saving' default config
com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: com.cloudera.utils.hadoop.hms.mirror.Config["optimization"]->com.cloudera.utils.hadoop.hms.mirror.Optimization["skipStatsCollection"])
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:392)
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:351)
        at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:316)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:782)
        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:774)
        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
        at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4568)
        at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3821)
        at com.cloudera.utils.hadoop.hms.mirror.Config.setup(Config.java:267)
        at com.cloudera.utils.hadoop.hms.Mirror.init(Mirror.java:305)
        at com.cloudera.utils.hadoop.hms.Mirror.go(Mirror.java:2156)
        at com.cloudera.utils.hadoop.hms.Mirror.main(Mirror.java:2209)
        Suppressed: org.yaml.snakeyaml.emitter.EmitterException: expected NodeEvent, but got <org.yaml.snakeyaml.events.DocumentEndEvent()>
                at org.yaml.snakeyaml.emitter.Emitter.expectNode(Emitter.java:474)
                at org.yaml.snakeyaml.emitter.Emitter.access$1800(Emitter.java:72)
                at org.yaml.snakeyaml.emitter.Emitter$ExpectBlockMappingKey.expect(Emitter.java:752)
                at org.yaml.snakeyaml.emitter.Emitter.emit(Emitter.java:256)
                at com.fasterxml.jackson.dataformat.yaml.YAMLGenerator._emit(YAMLGenerator.java:969)
                at com.fasterxml.jackson.dataformat.yaml.YAMLGenerator._emitEndDocument(YAMLGenerator.java:964)
                at com.fasterxml.jackson.dataformat.yaml.YAMLGenerator.close(YAMLGenerator.java:489)
                at com.fasterxml.jackson.databind.util.ClassUtil.closeOnFailAndThrowAsIOE(ClassUtil.java:497)
                at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4570)
                ... 5 more
Caused by: java.lang.NullPointerException
        at com.cloudera.utils.hadoop.hms.mirror.Optimization.getSkipStatsCollection(Optimization.java:78)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:689)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:774)
        ... 12 more

**Comment by dstreev** [comment]
fixed
